### ISSUE TITLE
bug: the icon to remove items from a multi-select property is hidden

### ISSUE THREAD

**Issue by morganmsrn** [Benature/obsidian-metadata-icon#5]
The cross icon at the right of an item in a multi-select property seems to be invisible because of the `hidden` placed upon `metadata-property`.

I suppose placing the `hidden` on the `meta-property-icon` directly should resolve this ?

https://github.com/Benature/obsidian-metadata-icon/blob/1081992628e73d592522144443984b1b00c9602b/main.ts#L88

<img width="526" alt="screenshot 2024-04-11 at 01 54 46" src="https://github.com/Benature/obsidian-metadata-icon/assets/64360101/78c0bc10-a35d-4729-8c33-f00454b2281d">

**Comment by Benature** [comment]
Indeed, thank you! this should be fixed in 0.0.15 :)
